version: "3.7"

x-app-volumes: &app-volumes
  - .:/usr/src/app:cached
  - ~/.bash_history:/root/.bash_history

x-app-environment: &app-environment
  - DB_HOST=db
  - DB_NAME=app_dev
  - DB_USER=postgres
  - TG_TOKEN
  - HOST
  - CHAT_ID

services:
  app:
    build: .
    command: "lein ring server"
    volumes: *app-volumes
    environment: *app-environment
    ports:
      - "3001:3000"
      - "4001:4001"
      - "5309:5309"
      - "5310:5310"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
