apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.service.name }}
    spec:
      initContainers:
      - name: migrations
        image: {{ .Values.image }}:{{ .Values.version }}
        command: ['lein', 'migratus', "migrate"]

        env:
{{- range $key, $value := $.Values.envVars }}
        - name: {{ $key }}
          value: {{ $value | quote }}
{{ end }}

      containers:
      - name: bot
        command: ["java"]
        args: ["-jar", "server.jar"]
        image: {{ .Values.image }}:{{ .Values.version }}
        ports:
        - containerPort: {{ .Values.port }}

        readinessProbe:
          httpGet:
            path: /index.html
            port: {{ .Values.port }}

        env:
{{- range $key, $value := $.Values.envVars }}
        - name: {{ $key }}
          value: {{ $value | quote }}
{{ end }}
